# SPDX-License-Identifier: GPL-2.0+

obj-y += board.o
obj-y += lowlevel_init.o
obj-y += rtkit.o
obj-$(CONFIG_APPLE_HANDOFF) += handoff.o
obj-$(CONFIG_WDT_APPLE_PRESERVE_INHERITED_STATE) += wdt_inherited.o
obj-$(CONFIG_APPLE_MTP_KEYB) += rtkit_helper.o
obj-$(CONFIG_NVME_APPLE) += sart.o
